---
title: "My first post!"
date: 2018-07-13
---

title: Font Blog
author: Daniel Roncari  
email: roncari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about fonts. From a different perspective. 

# social links
twitter_username: roncari
github_username:  roncari

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
